2017-09-07 14:53:18,378 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 16:35:29,298 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 16:35:29,323 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 16:35:29,802 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 17:05:55,661 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 17:05:55,688 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 17:15:26,187 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 17:15:26,194 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 17:15:26,253 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 17:15:26,895 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 18:37:28,542 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 18:37:28,772 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 18:37:28,930 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 18:37:29,709 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 19:57:46,141 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 20:04:52,819 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 20:04:54,006 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-07 22:58:04,128 stream error
Traceback (most recent call last):
  File "stream.py", line 51, in stream_to_json
    stream.filter(track=['jose'])
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 445, in filter
    self._start(async)
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 361, in _start
    self._run()
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 294, in _run
    raise exception
AttributeError: 'NoneType' object has no attribute 'strip'
2017-09-08 00:47:34,454 stream error
Traceback (most recent call last):
  File "stream.py", line 51, in stream_to_json
    stream.filter(track=['jose'])
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 445, in filter
    self._start(async)
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 361, in _start
    self._run()
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 294, in _run
    raise exception
ProtocolError: ('Connection broken: IncompleteRead(0 bytes read, 512 more expected)', IncompleteRead(0 bytes read, 512 more expected))
2017-09-08 00:58:08,740 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 00:58:09,132 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 00:58:09,355 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 00:58:10,157 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 00:58:45,967 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 01:02:04,641 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 01:02:05,296 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 01:02:07,188 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 01:02:08,194 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 01:42:22,543 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 01:42:23,107 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 01:42:23,516 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 01:42:25,346 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 02:40:08,305 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 02:40:10,405 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 02:52:02,032 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 02:52:02,358 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 02:52:04,634 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 02:55:46,698 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 02:59:03,226 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 02:59:04,526 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 02:59:04,642 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 02:59:05,496 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 03:36:51,444 stream error
Traceback (most recent call last):
  File "stream.py", line 51, in stream_to_json
    stream.filter(track=['jose'])
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 445, in filter
    self._start(async)
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 361, in _start
    self._run()
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 294, in _run
    raise exception
ReadTimeoutError: HTTPSConnectionPool(host='stream.twitter.com', port=443): Read timed out.
2017-09-08 04:52:11,493 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 04:52:14,313 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 05:26:26,137 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 05:35:10,773 stream error
Traceback (most recent call last):
  File "stream.py", line 51, in stream_to_json
    stream.filter(track=['jose'])
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 445, in filter
    self._start(async)
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 361, in _start
    self._run()
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 294, in _run
    raise exception
ReadTimeoutError: HTTPSConnectionPool(host='stream.twitter.com', port=443): Read timed out.
2017-09-08 05:35:23,163 stream error
Traceback (most recent call last):
  File "stream.py", line 51, in stream_to_json
    stream.filter(track=['jose'])
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 445, in filter
    self._start(async)
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 361, in _start
    self._run()
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 294, in _run
    raise exception
error: [Errno 10054] An existing connection was forcibly closed by the remote host
2017-09-08 05:47:37,346 stream error
Traceback (most recent call last):
  File "stream.py", line 51, in stream_to_json
    stream.filter(track=['jose'])
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 445, in filter
    self._start(async)
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 361, in _start
    self._run()
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 294, in _run
    raise exception
ProtocolError: ('Connection broken: IncompleteRead(0 bytes read, 4048 more expected)', IncompleteRead(0 bytes read, 4048 more expected))
2017-09-08 05:49:51,098 stream error
Traceback (most recent call last):
  File "stream.py", line 51, in stream_to_json
    stream.filter(track=['jose'])
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 445, in filter
    self._start(async)
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 361, in _start
    self._run()
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 294, in _run
    raise exception
error: [Errno 10054] An existing connection was forcibly closed by the remote host
2017-09-08 05:51:27,086 stream error
Traceback (most recent call last):
  File "stream.py", line 51, in stream_to_json
    stream.filter(track=['jose'])
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 445, in filter
    self._start(async)
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 361, in _start
    self._run()
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 294, in _run
    raise exception
error: [Errno 10054] An existing connection was forcibly closed by the remote host
2017-09-08 06:54:39,803 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 06:54:40,707 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 07:11:55,960 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 08:07:38,914 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 08:07:40,479 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 08:25:47,881 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 08:25:49,638 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 10:24:36,003 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 10:57:37,796 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 11:12:48,841 data error
Traceback (most recent call last):
  File "stream.py", line 22, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 12:42:34,315 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:14:08,039 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:14:08,040 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:14:08,042 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:14:08,056 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:37:51,089 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:37:51,200 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:37:51,388 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:37:51,407 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:50:32,105 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:50:32,229 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:50:32,552 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:50:33,132 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:54:23,184 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:54:23,191 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:54:23,220 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 13:54:23,288 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 14:10:11,253 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 14:10:11,378 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 14:10:12,444 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 14:10:12,694 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 14:14:23,460 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 14:22:34,575 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 14:22:35,492 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 14:35:31,359 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 14:35:31,913 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 14:35:32,808 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 14:51:43,723 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:28:44,029 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:28:46,456 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:31:23,342 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:31:23,349 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:31:23,378 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:31:23,414 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:34:00,457 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:34:00,516 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:34:00,736 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:34:02,505 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:54:43,575 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:54:43,582 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:54:43,690 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:54:44,750 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:56:31,651 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:56:32,226 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 15:59:36,737 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 16:13:30,678 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 16:13:31,348 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 16:13:31,707 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 16:13:36,536 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 16:47:28,654 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 16:47:29,174 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 16:47:29,286 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 16:47:29,716 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 17:25:55,138 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 17:25:56,459 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 17:25:58,233 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 17:26:00,720 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 17:56:58,138 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 17:56:58,404 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 17:56:58,411 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
2017-09-08 17:56:59,713 data error
Traceback (most recent call last):
  File "stream.py", line 27, in on_data
    print '%s @%s: %s' % (decoded['created_at'][:-11], decoded['user']['screen_name'], decoded['text'].encode('ascii', 'ignore'))
KeyError: 'created_at'
